# Generated by Django 5.2.12 on 2026-03-22 01:49

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('current_status', models.CharField(choices=[('draft', 'Borrador'), ('reported', 'Reportada'), ('under_review', 'En revision'), ('action_plan_pending', 'Plan pendiente'), ('in_progress', 'En ejecucion'), ('pending_verification', 'Pendiente de verificacion'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], default='draft', max_length=40)),
                ('detected_at', models.DateTimeField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('root_cause_summary', models.TextField(blank=True)),
                ('resolution_summary', models.TextField(blank=True)),
                ('anomaly_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.anomalyorigin')),
                ('anomaly_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.anomalytype')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.area')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='anomalies.anomaly')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.line')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_anomalies', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.priority')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_anomalies', to=settings.AUTH_USER_MODEL)),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.severity')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomalies', to='catalog.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalia',
                'verbose_name_plural': 'Anomalias',
                'ordering': ('-detected_at', 'code'),
            },
        ),
        migrations.CreateModel(
            name='AnomalyAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=common.storage.anomaly_attachment_upload_to)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='anomalies.anomaly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adjunto de anomalia',
                'verbose_name_plural': 'Adjuntos de anomalia',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnomalyComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('body', models.TextField()),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anomalies.anomaly')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly_comments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de anomalia',
                'verbose_name_plural': 'Comentarios de anomalia',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AnomalyStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('from_status', models.CharField(choices=[('draft', 'Borrador'), ('reported', 'Reportada'), ('under_review', 'En revision'), ('action_plan_pending', 'Plan pendiente'), ('in_progress', 'En ejecucion'), ('pending_verification', 'Pendiente de verificacion'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], max_length=40)),
                ('to_status', models.CharField(choices=[('draft', 'Borrador'), ('reported', 'Reportada'), ('under_review', 'En revision'), ('action_plan_pending', 'Plan pendiente'), ('in_progress', 'En ejecucion'), ('pending_verification', 'Pendiente de verificacion'), ('closed', 'Cerrada'), ('cancelled', 'Cancelada')], max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField()),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='anomalies.anomaly')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly_status_changes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ('-changed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['current_status', 'priority', 'area'], name='anom_status_prio_area_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['code'], name='anom_code_idx'),
        ),
        migrations.AddIndex(
            model_name='anomaly',
            index=models.Index(fields=['detected_at'], name='anom_detected_idx'),
        ),
    ]
