# Generated by Django 5.2.12 on 2026-04-03 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0005_alter_anomaly_severity_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyImmediateAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('action_date', models.DateField()),
                ('effectiveness_verified_at', models.DateTimeField()),
                ('observation', models.TextField()),
                ('actions_taken', models.TextField()),
                ('effectiveness_comment', models.TextField(blank=True)),
                ('closure_comment', models.TextField(blank=True)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immediate_action', to='anomalies.anomaly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anomaly_immediate_actions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accion inmediata de anomalia',
                'verbose_name_plural': 'Acciones inmediatas de anomalia',
            },
        ),
    ]
