# Generated by Django 5.2.7 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomalies", "0007_anomalycodereservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomaly",
            name="classification_change_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="classification_change_unlocked",
            field=models.BooleanField(default=False),
        ),
    ]
