# Generated by Django 5.2.12 on 2026-04-21 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0008_anomaly_classification_change_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='current_stage',
            field=models.CharField(choices=[('registration', 'Registro'), ('containment', 'Contencion'), ('initial_verification', 'Verificacion inicial'), ('classification', 'REVICION DE HALLAZGOS'), ('treatment_created', 'Tratamiento creado'), ('cause_analysis', 'Analisis de causa'), ('proposals', 'Propuestas'), ('action_plan', 'Plan de accion'), ('execution_follow_up', 'Ejecucion y seguimiento'), ('results', 'Resultados'), ('effectiveness_verification', 'Verificacion de eficacia'), ('closure', 'Cierre'), ('standardization_learning', 'Estandarizacion y aprendizaje')], default='registration', max_length=40),
        ),
        migrations.AlterField(
            model_name='anomalycodereservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomalycodereservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomalyeffectivenesscheck',
            name='recommended_stage',
            field=models.CharField(blank=True, choices=[('registration', 'Registro'), ('containment', 'Contencion'), ('initial_verification', 'Verificacion inicial'), ('classification', 'REVICION DE HALLAZGOS'), ('treatment_created', 'Tratamiento creado'), ('cause_analysis', 'Analisis de causa'), ('proposals', 'Propuestas'), ('action_plan', 'Plan de accion'), ('execution_follow_up', 'Ejecucion y seguimiento'), ('results', 'Resultados'), ('effectiveness_verification', 'Verificacion de eficacia'), ('closure', 'Cierre'), ('standardization_learning', 'Estandarizacion y aprendizaje')], max_length=40),
        ),
        migrations.AlterField(
            model_name='anomalystatushistory',
            name='from_stage',
            field=models.CharField(choices=[('registration', 'Registro'), ('containment', 'Contencion'), ('initial_verification', 'Verificacion inicial'), ('classification', 'REVICION DE HALLAZGOS'), ('treatment_created', 'Tratamiento creado'), ('cause_analysis', 'Analisis de causa'), ('proposals', 'Propuestas'), ('action_plan', 'Plan de accion'), ('execution_follow_up', 'Ejecucion y seguimiento'), ('results', 'Resultados'), ('effectiveness_verification', 'Verificacion de eficacia'), ('closure', 'Cierre'), ('standardization_learning', 'Estandarizacion y aprendizaje')], max_length=40),
        ),
        migrations.AlterField(
            model_name='anomalystatushistory',
            name='to_stage',
            field=models.CharField(choices=[('registration', 'Registro'), ('containment', 'Contencion'), ('initial_verification', 'Verificacion inicial'), ('classification', 'REVICION DE HALLAZGOS'), ('treatment_created', 'Tratamiento creado'), ('cause_analysis', 'Analisis de causa'), ('proposals', 'Propuestas'), ('action_plan', 'Plan de accion'), ('execution_follow_up', 'Ejecucion y seguimiento'), ('results', 'Resultados'), ('effectiveness_verification', 'Verificacion de eficacia'), ('closure', 'Cierre'), ('standardization_learning', 'Estandarizacion y aprendizaje')], max_length=40),
        ),
    ]
