# Generated by Django 5.2.12 on 2026-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalies', '0009_alter_anomaly_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalystatushistory',
            name='evidence_note',
            field=models.TextField(blank=True),
        ),
    ]
