# Generated by Django 5.2.17 on 2026-09-14 14:20

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomalies", "0018_observationaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="anomalylearning", name="document_changes"),
        migrations.RemoveField(model_name="anomalylearning", name="lessons_learned"),
        migrations.RemoveField(model_name="anomalylearning", name="shared_at"),
        migrations.RemoveField(model_name="anomalylearning", name="shared_with"),
        migrations.RemoveField(model_name="anomalylearning", name="standardization_actions"),
        migrations.AddField(
            model_name="anomalylearning",
            name="has_learning",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anomalylearning",
            name="learned_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="anomalylearning",
            name="no_learning_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="anomalylearning",
            name="procedure_modification_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="anomalylearning",
            name="procedure_modified",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnomalyLearningEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_version", models.PositiveIntegerField(default=1)),
                ("file", models.FileField(upload_to=common.storage.anomaly_learned_lesson_evidence_upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "learned_lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="anomalies.anomalylearning",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anomaly_learned_lesson_evidences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de leccion aprendida de Observacion",
                "verbose_name_plural": "Evidencias de lecciones aprendidas de Observaciones",
                "ordering": ("-created_at",),
            },
        ),
    ]
