# Generated by Django 5.2 on 2026-08-28

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicatorReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_version", models.PositiveIntegerField(default=1)),
                ("indicator_key", models.SlugField(max_length=80)),
                ("period_from", models.DateField()),
                ("period_to", models.DateField()),
                ("filters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("ready", "Generado"),
                            ("queued", "Encolado"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("report_file", models.FileField(blank=True, null=True, upload_to=common.storage.indicator_report_upload_to)),
                ("original_name", models.CharField(blank=True, default="", max_length=255)),
                ("content_type", models.CharField(blank=True, default="application/pdf", max_length=100)),
                ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de indicador",
                "verbose_name_plural": "Informes de indicadores",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["indicator_key", "period_from", "period_to"], name="ind_report_period_idx"),
                    models.Index(fields=["status", "created_at"], name="ind_report_status_idx"),
                ],
            },
        ),
    ]
