# Generated by Django 5.2.12 on 2026-05-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_core_catalogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalytype',
            options={'ordering': ('display_order', 'name'), 'verbose_name': 'Tipo de desvio', 'verbose_name_plural': 'Tipos de desvio'},
        ),
    ]
