# Generated by Codex on 2026-05-12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_anomaly_type_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="anomalyorigin",
            options={
                "ordering": ("display_order", "name"),
                "verbose_name": "Imputacion de anomalia",
                "verbose_name_plural": "Imputaciones de anomalia",
            },
        ),
        migrations.AlterModelOptions(
            name="priority",
            options={
                "ordering": ("display_order", "name"),
                "verbose_name": "Orden operativo",
                "verbose_name_plural": "Orden operativo",
            },
        ),
    ]
