export const DOCUMENTED_INFORMATION_GUIDE = {
  title: "Guía sobre los requisitos de información documentada de ISO 9001:2015",
  introduction: [
    "ISO 9001:2015 busca que la documentación sea más simple y proporcional a cada empresa. No exige un “sistema de documentos”, sino un sistema de gestión de la calidad documentado.",
    "Cada organización define cuánta información necesita para demostrar que sus procesos se planifican, operan, controlan y mejoran eficazmente.",
  ],
  purposes: [
    "Comunicar instrucciones, criterios y responsabilidades.",
    "Demostrar que lo planificado realmente se realizó.",
    "Compartir conocimiento y conservar experiencias técnicas.",
    "Preservar especificaciones, aprendizajes y antecedentes para futuros productos o procesos.",
  ],
  media: "Puede estar en cualquier soporte: papel, archivos electrónicos, fotografías, discos, muestras patrón, etc.",
  organizationResponsibilities: [
    "Mantener información para que los procesos puedan operar correctamente.",
    "Conservar información como evidencia de que los procesos se ejecutaron según lo previsto.",
  ],
  proportionality: "La cantidad de documentación dependerá del tamaño de la empresa, la complejidad de sus procesos e interacciones y la competencia de las personas.",
  valuableDocuments: [
    "Mapas de proceso",
    "Procedimientos",
    "Instrucciones de trabajo",
    "Especificaciones",
    "Comunicaciones internas",
    "Planes de producción",
    "Listas de proveedores aprobados",
    "Planes de inspección",
    "Formularios",
    "Manuales",
  ],
  evidenceRecords: [
    "Competencia",
    "Calibraciones",
    "Proveedores",
    "Trazabilidad",
    "Cambios de producción",
    "Liberación de productos",
    "Auditorías",
    "Revisión por la dirección",
    "No conformidades",
  ],
  nonConformityRecords: [
    "La naturaleza de la no conformidad.",
    "Las acciones tomadas y las posteriores.",
    "Las concesiones obtenidas, si las hubiera.",
    "Quién tuvo autoridad para decidir la disposición.",
    "El resultado de las acciones correctivas.",
  ],
  processFirst: "ISO remarca que la empresa debe analizar primero sus procesos y recién después definir qué documentación necesita. No se debe diseñar el proceso para “llenar papeles”.",
  auditEvidence: "Para una auditoría o certificación, no es necesario tener documentación excesiva, pero sí poder aportar evidencia objetiva de que el sistema funciona. Esa evidencia puede provenir de observaciones, mediciones, ensayos, registros y otros medios verificables.",
  systemFocus: "El sistema debe ser, ante todo, el lugar donde queda la evidencia objetiva y trazable de cómo Schneider detecta, analiza, trata, verifica y cierra una anomalía.",
  systemRecommendations: [
    { requirement: "Registro íntegro de la anomalía", application: "Fecha/hora automática, origen, proceso, producto/lote si aplica, descripción, fotos o archivos, quien informa y responsable." },
    { requirement: "Trazabilidad total", application: "Historial inalterable de cada cambio: estado anterior/nuevo, usuario, fecha, comentario, adjuntos y decisiones." },
    { requirement: "Clasificación controlada", application: "Mantener las clasificaciones definidas: Observación, Tratamiento, Oportunidad de mejora, futuras e Inválida." },
    { requirement: "Reglas de negocio en backend", application: "No depender solo de la pantalla: las validaciones deben impedir guardar decisiones incompletas o incompatibles." },
    { requirement: "Caminos excluyentes", application: "Observación y Tratamiento deben permanecer mutuamente excluyentes usando observation_resolution_path como fuente de verdad." },
    { requirement: "Responsabilidad clara", application: "Toda clasificación válida debe tener responsable; una clasificación Inválida exige motivo, fecha del servidor y cierre definitivo por administración." },
    { requirement: "Plan y ejecución", application: "Para Observación: responsable, fecha límite y texto; luego acciones tomadas, fecha, detalle, evidencias y verificación." },
    { requirement: "Verificación de eficacia", application: "Debe registrar fecha, resultado Sí/No y observación. Si no fue eficaz, la anomalía no puede cerrarse: debe volver a requerir acción." },
    { requirement: "Cierre con autoridad", application: "Identificar quién verificó, quién autorizó el cierre y bajo qué evidencia." },
    { requirement: "Evidencias adjuntas", application: "Fotos, documentos, mediciones, actas, controles, correos o reportes deben quedar vinculados a la anomalía y conservar su contexto." },
    { requirement: "Indicadores y aprendizaje", application: "Poder medir reincidencias, plazos vencidos, eficacia de acciones, causas frecuentes, sector/origen y tiempo de cierre." },
    { requirement: "Gestión documental", application: "Para procedimientos, instrucciones o especificaciones vinculadas: versión, vigencia, aprobador, historial de cambios y acceso a la versión vigente." },
    { requirement: "Auditoría", application: "Debe poder obtenerse un reporte completo por anomalía, proceso, período, responsable o estado, sin reconstruir datos manualmente." },
  ],
} as const;
