# Generated by Django 5.2.12 on 2026-03-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_and_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(choices=[('usuario_activo', 'Usuario activo'), ('mando_medio_activo', 'Mando medio activo'), ('administrador', 'Administrador'), ('desarrollador', 'Desarrollador')], default='usuario_activo', max_length=30),
        ),
    ]
