# Generated by Django 5.2.12 on 2026-03-22 01:49

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalies', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='action_items', to='catalog.actiontype')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='action_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accion',
                'verbose_name_plural': 'Acciones',
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ActionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('evidence_type', models.CharField(default='file', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=common.storage.action_evidence_upload_to)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('action_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='actions.actionitem')),
            ],
            options={
                'verbose_name': 'Evidencia de accion',
                'verbose_name_plural': 'Evidencias de accion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='anomalies.anomaly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_action_plans', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de accion',
                'verbose_name_plural': 'Planes de accion',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='actionitem',
            name='action_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='actions.actionplan'),
        ),
        migrations.AddConstraint(
            model_name='actionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('anomaly',), name='act_active_plan_anom_uq'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['status', 'due_date', 'assigned_to'], name='act_status_due_asg_idx'),
        ),
        migrations.AddConstraint(
            model_name='actionitem',
            constraint=models.UniqueConstraint(fields=('action_plan', 'sequence'), name='act_plan_seq_uq'),
        ),
    ]
