# Generated by Django 5.2.12 on 2026-03-30 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_alter_actionitem_status'),
        ('anomalies', '0005_alter_anomaly_severity_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('scheduled', 'Programado'), ('in_progress', 'En tratamiento'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('method_used', models.CharField(blank=True, choices=[('five_whys', '5 Why'), ('6m', '6M'), ('ishikawa', 'Ishikawa'), ('a3', 'A3'), ('8d', '8D'), ('other', 'Otro')], default='', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('primary_anomaly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_treatments', to='anomalies.anomaly')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TreatmentAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_links', to='anomalies.anomaly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_links', to='actions.treatment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalia asociada a tratamiento',
                'verbose_name_plural': 'Anomalias asociadas a tratamientos',
            },
        ),
        migrations.CreateModel(
            name='TreatmentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('role', models.CharField(choices=[('convoked', 'Convocado'), ('facilitator', 'Facilitador'), ('owner', 'Responsable')], default='convoked', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='actions.treatment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participante de tratamiento',
                'verbose_name_plural': 'Participantes de tratamiento',
            },
        ),
        migrations.CreateModel(
            name='TreatmentRootCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='actions.treatment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Causa raiz de tratamiento',
                'verbose_name_plural': 'Causas raiz de tratamiento',
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TreatmentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_tasks', to=settings.AUTH_USER_MODEL)),
                ('root_cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='actions.treatmentrootcause')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='actions.treatment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de tratamiento',
                'verbose_name_plural': 'Tareas de tratamiento',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TreatmentTaskAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_task_links', to='anomalies.anomaly')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_links', to='actions.treatmenttask')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalia vinculada a tarea',
                'verbose_name_plural': 'Anomalias vinculadas a tareas',
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['status', 'scheduled_for'], name='trt_status_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['code'], name='trt_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentanomaly',
            constraint=models.UniqueConstraint(fields=('treatment', 'anomaly'), name='trt_anom_uq'),
        ),
        migrations.AddConstraint(
            model_name='treatmentparticipant',
            constraint=models.UniqueConstraint(fields=('treatment', 'user'), name='trt_user_uq'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrootcause',
            constraint=models.UniqueConstraint(fields=('treatment', 'sequence'), name='trt_root_seq_uq'),
        ),
        migrations.AddConstraint(
            model_name='treatmenttask',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='trt_task_code_uq'),
        ),
        migrations.AddConstraint(
            model_name='treatmenttaskanomaly',
            constraint=models.UniqueConstraint(fields=('task', 'anomaly'), name='trt_task_anom_uq'),
        ),
    ]
