# Generated by Django 5.2.12 on 2026-04-02 12:00

import common.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0004_treatment_treatmentanomaly_treatmentparticipant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_version", models.PositiveIntegerField(default=1)),
                ("file", models.FileField(upload_to=common.storage.treatment_evidence_upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("treatment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidences", to="actions.treatment")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="treatment_evidences", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Evidencia de tratamiento",
                "verbose_name_plural": "Evidencias de tratamiento",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TreatmentTaskEvidence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_version", models.PositiveIntegerField(default=1)),
                ("file", models.FileField(upload_to=common.storage.treatment_task_evidence_upload_to)),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL)),
                ("treatment_task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidences", to="actions.treatmenttask")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL)),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="treatment_task_evidences", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Evidencia de tarea de tratamiento",
                "verbose_name_plural": "Evidencias de tareas de tratamiento",
                "ordering": ("-created_at",),
            },
        ),
    ]
