# Generated by Django 5.2.12 on 2026-04-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_treatment_effectiveness_evaluation_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='effectiveness_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='effectiveness_validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_effectiveness_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='effectiveness_validation_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='effectiveness_validation_result',
            field=models.CharField(blank=True, choices=[('effective', 'Eficaz'), ('not_effective', 'No eficaz')], default='', max_length=20),
        ),
    ]
