# Generated by Django 5.2.12 on 2026-05-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_treatment_effectiveness_validated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmenttask',
            name='root_causes',
            field=models.ManyToManyField(blank=True, related_name='task_links', to='actions.treatmentrootcause'),
        ),
    ]
